project:
  type: book
  output-dir: docs
book:
  title: "Advanced Research Methods Cookbook"
  author: "Cristina Rivera"
  date: "10/1/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "PCA"
      chapters:
        - method_exp.qmd
        - about_data.qmd
        - interpret_data.qmd
    - part: "Correspondance Analysis"
      chapters: 
        - method_exp_CA.qmd
        - about_data_CA.qmd
        - interpret_data_CA.qmd
        - Symmetric vs Assym.qmd
        - Bootstrap.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

